name: 'Log Metric'
description: 'Log data point to a metric with the provided value. If the metric is not there, it will create one.'
inputs:
  metric-name:
    description: 'target metric name'
    required: true
  value:
    description: 'the value to log to the metric'
    required: true
  role-to-assume:
    description: 'target AWS account IAM role to assume'
    required: true
  aws-region:
    description: 'target AWS account region'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # v2.0.0 https://github.com/aws-actions/configure-aws-credentials/commit/e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
    - shell: bash
      run: aws cloudwatch put-metric-data --metric-name "$metric_name" --namespace GithubCanaryApps --value "$value"
      env:
        metric_name: ${{ inputs.metric-name }}
        value: ${{ inputs.value }}
