name: Liveness Release Branch Sync

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  branch-sync:
    name: Branch Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync branches
        uses: repo-sync/pull-request@v2
        id: open-pr
        with:
          source_branch: main
          destination_branch: liveness-release
          pr_title: 'Sync branch main to liveness-release'
          github_token: ${{ secrets.GITHUB_TOKEN }}
