# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Liveness Tests

on:
  push:
    branches: [liveness-main]

  pull_request:
    branches: [liveness-main]

jobs:
  unit:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    env:
      NODE_ENV: test

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        package:
          - '@aws-amplify/ui'
          - '@aws-amplify/ui-angular'
          - '@aws-amplify/ui-vue'
          - '@aws-amplify/ui-react'

    steps:
      - name: Checkout Amplify UI
        uses: actions/checkout@v2

      - name: Configure CodeArtifact
        id: configure-codeartifact
        uses: ./.github/actions/codeartifact-action
        with:
          role-to-assume: ${{ secrets.LIVENESS_DEPLOYMENT_ROLE }}
          domain: amplify-ui-liveness
          repository: amplify-ui

      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'
          registry-url: ${{ steps.configure-codeartifact.outputs.repository-endpoint }}
          always-auth: true

      - name: Install packages
        run: yarn --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ steps.configure-codeartifact.outputs.repository-token }}

      - name: Lint packages
        run: yarn workspace ${{ matrix.package }} lint

      - name: Build ${{ matrix.package }} package
        run: yarn workspace ${{ matrix.package }} build

      - name: Run ${{ matrix.package }} tests
        run: yarn workspace ${{ matrix.package}} test
