# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Liveness Tests

on:
  push:
    branches: [liveness-main]

  pull_request:
    branches: [liveness-main]

permissions:
  pull-requests: write # used to remove label
  id-token: write
  contents: write
  # other permissions are defaulted to "none"

jobs:
  setup:
    runs-on: ubuntu-latest
    # We run tests only if it's:
    #   1) push to main, or
    #   2) pull request not from a fork (ie. internal PR), or
    #   3) pull request from a fork (ie. external PR) that was added "run-tests" label
    if: |
      github.event_name == 'push' ||
      (github.event.pull_request.head.repo.full_name == github.repository) || 
      (github.event.action == 'labeled' && github.event.label.name == 'run-tests')
    outputs:
      ref: ${{ steps.get-ref.outputs.ref }}
      commit: ${{ steps.get-ref.outputs.commit }}
    steps:
      # This would be a good place to run and cache `yarn`, `yarn build`, etc
      - name: Remove run-tests label, if applicable
        if: always() && github.event.label.name == 'run-tests'
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo } } = context;
            const label = 'run-tests';
            github.issues.removeLabel({ owner, repo, issue_number, name: label });
      - name: Checkout Amplify UI
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get-ref.outputs.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false

      - name: Configure CodeArtifact
        id: configure-codeartifact
        uses: ./.github/actions/codeartifact-action
        with:
          role-to-assume: ${{ secrets.LIVENESS_DEPLOYMENT_ROLE }}
          domain: amplify-ui-liveness
          repository: amplify-ui

      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'
          registry-url: ${{ steps.configure-codeartifact.outputs.repository-endpoint }}
          always-auth: true
      - name: Get ref and commit
        id: get-ref
        run: |
          echo "::set-output name=key::${{ github.event_name == 'push' && github.ref || github.event.pull_request.head.ref }}"
          echo "::set-output name=commit::$(git rev-parse --short "$GITHUB_SHA")"
      - name: Install packages
        run: yarn --frozen-lockfile --prefer-offline
      - name: Build ui package
        run: yarn ui build
      - name: Cache cypress runner
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('yarn.lock') }}
      - name: Cache packages/ui/dist
        uses: actions/cache@v2
        with:
          path: ./packages/ui/dist
          key: ${{ runner.os }}-ui-${{ steps.get-ref.outputs.commit }}
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
            **/node_modules
          key: ${{ runner.os }}-nodemodules-${{ steps.get-ref.outputs.commit }}

  unit:
    needs: setup
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        package:
          - ui
          - angular
          - vue
          - react

    steps:
      - name: Checkout Amplify UI
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event_name == 'push' && github.ref || github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          persist-credentials: false

      - name: Configure CodeArtifact
        id: configure-codeartifact
        uses: ./.github/actions/codeartifact-action
        with:
          role-to-assume: ${{ secrets.LIVENESS_DEPLOYMENT_ROLE }}
          domain: amplify-ui-liveness
          repository: amplify-ui

      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'
          registry-url: ${{ steps.configure-codeartifact.outputs.repository-endpoint }}
          always-auth: true

      - name: Restore node_modules cache
        uses: actions/cache@v2
        id: restore-cache
        with:
          path: |
            ./node_modules
            **/node_modules
          key: ${{ runner.os }}-nodemodules-${{ needs.setup.outputs.commit }}

      - name: Restore ui/dist cache
        uses: actions/cache@v2
        id: restore-ui-cache
        with:
          path: ./packages/ui/dist
          key: ${{ runner.os }}-ui-${{ needs.setup.outputs.commit }}

      - name: Install packages
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --prefer-offline  --prefer-offline

      - name: Build ui package
        if: ${{ steps.restore-ui-cache.outputs.cache-hit != 'true' && matrix.package != 'ui' }}
        run: yarn ui build

      - name: Build ${{ matrix.package }} package
        if: ${{ matrix.package != '@aws-amplify/ui' }}
        run: yarn ${{ matrix.package }} build

      - name: Cache ${{ matrix.package }}/dist
        uses: actions/cache@v2
        with:
          path: ./packages/${{ matrix.package }}/dist
          key: ${{ runner.os }}-${{ matrix.package }}-${{ needs.setup.outputs.commit }}

      - name: Lint packages
        run: yarn ${{ matrix.package }} lint

      - name: Run ${{ matrix.package }} tests
        run: yarn ${{ matrix.package }} test
