# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Liveness Tests

on:
  push:
    branches: [liveness-main]

  pull_request:
    branches: [liveness-main]

jobs:
  unit:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        package:
          - '@aws-amplify/ui'
          - '@aws-amplify/ui-angular'
          - '@aws-amplify/ui-vue'
          - '@aws-amplify/ui-react'

    steps:
      - name: Checkout Amplify UI
        uses: actions/checkout@v2

      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Lint packages
        run: yarn workspace ${{ matrix.package }} lint

      - name: Build ${{ matrix.package }} package
        run: yarn workspace ${{ matrix.package }} build

      - name: Run ${{ matrix.package }} tests
        run: yarn workspace ${{ matrix.package}} test
