# Description: This workflow tests github workflows credential for metric logger for POC purposes.
#              This file and the branch can be reverted before PR2613 merged onto `main`.

name: POC / Github Workflows Cred

on:
  push:
    branches: [poc/gh-workflow/metric-logger-cred]

permissions:
  contents: write # Used to push tags to GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    strategy:
      fail-fast: false
      matrix:
        # Paths for each example app we want to test build on
        path:
          - angular/angularcli
          - react/cra
          - react/cra-ts
          - react/next
          - react/vite
          - react/vite3
          - vue/vite
          - vue/vite3
          - vue/vuecli
    steps:
      - name: Checkout Amplify UI
        uses: actions/checkout@v3
        with:
          persist-credentials: false

  log-metric:
    # Send data point to metricRunTimeTestsFailure in github-workflows@ us-east-2, if it's a failure
    runs-on: ubuntu-latest
    environment: ci
    needs: build
    steps:
      - name: Set Value
        id: set-value
        run: echo "set Value"
        env:
          VALUE: 'some value'
      - name: Get Value
        run: echo ${{ env.VALUE }}
      - name: Log failure data point to metric PublishLatestFailure
        if: ${{ failure() }}
        uses: aws-amplify/amplify-ui/.github/actions/log-metric@poc/gh-workflow/metric-logger-cred
        with:
          metric-name: PublishLatestFailure
          value: 1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_METRIC_LOGGER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_METRIC_LOGGER }}
          AWS_REGION: us-east-2
      - name: Log success data point to metric PublishLatestFailure
        if: ${{ success() }}
        uses: aws-amplify/amplify-ui/.github/actions/log-metric@poc/gh-workflow/metric-logger-cred
        with:
          metric-name: PublishLatestFailure
          value: 0
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_METRIC_LOGGER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_METRIC_LOGGER }}
          AWS_REGION: us-east-2
