# Description: This workflow runs unit + e2e tests
#
# Triggered by: merge to `rna/release` branch

name: Publish / Geo Subpath

on:
  push:
    branches: [poc/geo-subpath]

jobs:
  publish:
    uses: ./.github/workflows/reusable-tagged-publish.yml
    with:
      dist-tag: geo-subpath
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
