# Description: This is a POC for running the React Native canary for Android

name: POC / RN Canary - Android

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Run yarn install on sample app
        run: yarn install
        working-directory: ./canary/apps/react-native/canarytest
      - name: Build Android apk (debug)
        run: ./gradlew assemble
        working-directory: ./canary/apps/react-native/canarytest/android
      - name: Run Android
        run: yarn android
        working-directory: ./canary/apps/react-native/canarytest
