# Description: This is a POC for running the React Native canary for iOS

name: POC / RN Canary - iOS

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Run yarn install on sample app
        run: yarn install
        working-directory: ./canary/apps/react-native/canarytest
      - run: xcode-select -p
      - run: pod install
        working-directory: ios
        name: Install pod dependencies
      - name: Build iOS (debug)
        run: "xcodebuild \
          -workspace ios/canarytest.xcworkspace \
          -scheme canarytest \
          clean archive \
          -sdk iphoneos \
          -configuration Debug \
          -UseModernBuildSystem=NO \
          -archivePath $PWD/canarytest \
          CODE_SIGNING_ALLOWED=NO"
